FROM node:18.16.1-alpine

WORKDIR /app

ENV NODE_ENV production

COPY package*.json ./

RUN npm ci --only=production

COPY . .

# Ubah pemilik berkas dan folder npm cache
RUN chown -R node:node /app
RUN chown -R node:node /home/node

# ENV PORT=5000 \
#     DB_HOSTNAME=db-service-user \
#     DB_NAME=service-user \
#     DB_USERNAME=admin \
#     DB_PASSWORD=rahasia

USER node

EXPOSE 5000

CMD [ "npm", "start" ]
